# Generated by Django 3.2.6 on 2022-06-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='military_organization',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='performancemeasure',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
