# Generated by Django 3.2.6 on 2022-06-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_auto_20220622_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='wlans',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
