# Generated by Django 3.2.6 on 2022-06-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_accesspoint_wlans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='wlans',
        ),
    ]
