# Generated by Django 3.2.6 on 2022-07-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_accesspoint_wlans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='wlans',
            field=models.IntegerField(max_length=30),
        ),
    ]
