# Generated by Django 3.2.6 on 2022-08-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_alter_accesspoint_wlans'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='antennagain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
