# Generated by Django 3.2.6 on 2022-08-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_node_antennagain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='antennagain',
        ),
    ]
