# Generated by Django 3.2.6 on 2022-08-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_remove_node_antennagain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryOrganization',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'MilitaryOrganization',
                'verbose_name_plural': 'MilitaryOrganization',
                'db_table': 'MilitaryOrganization',
            },
        ),
    ]
