# Generated by Django 3.2.6 on 2022-08-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0009_militaryorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryorganization',
            name='kind',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('DirectCommander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DirectCommander', to='configurator.militaryorganization')),
                ('Similar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Similar', to='configurator.militaryorganization')),
            ],
            options={
                'verbose_name': 'RoleDefinition',
                'verbose_name_plural': 'RoleDefinition',
                'db_table': 'ORoleDefinition',
            },
        ),
        migrations.CreateModel(
            name='OperationalStandards',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Om', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryorganization')),
                ('RoleDefinition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.roledefinition')),
            ],
            options={
                'verbose_name': 'OperatingStandard',
                'verbose_name_plural': 'OperatingStandard',
                'db_table': 'OperatingStandard',
            },
        ),
    ]
