# Generated by Django 3.2.6 on 2022-08-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0010_auto_20220811_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roledefinition',
            name='DirectCommander',
        ),
        migrations.RemoveField(
            model_name='roledefinition',
            name='Similar',
        ),
        migrations.DeleteModel(
            name='OperationalStandards',
        ),
        migrations.DeleteModel(
            name='RoleDefinition',
        ),
    ]
