# Generated by Django 3.2.6 on 2022-08-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0011_auto_20220812_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='Commander',
            field=models.ManyToManyField(blank=True, related_name='Commander', to='configurator.MilitaryOrganization'),
        ),
        migrations.AddField(
            model_name='node',
            name='Similar',
            field=models.ManyToManyField(blank=True, related_name='Similar', to='configurator.MilitaryOrganization'),
        ),
        migrations.AddField(
            model_name='node',
            name='Subordinate',
            field=models.ManyToManyField(blank=True, related_name='Subordinate', to='configurator.MilitaryOrganization'),
        ),
    ]
