# Generated by Django 3.2.6 on 2022-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0012_auto_20220812_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='Commander',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Similar',
        ),
        migrations.RemoveField(
            model_name='node',
            name='Subordinate',
        ),
        migrations.AddField(
            model_name='node',
            name='commander',
            field=models.ManyToManyField(blank=True, related_name='commander', to='configurator.MilitaryOrganization'),
        ),
        migrations.AddField(
            model_name='node',
            name='similar',
            field=models.ManyToManyField(blank=True, related_name='similar', to='configurator.MilitaryOrganization'),
        ),
        migrations.AddField(
            model_name='node',
            name='subordinate',
            field=models.ManyToManyField(blank=True, related_name='subordinate', to='configurator.MilitaryOrganization'),
        ),
        migrations.RemoveField(
            model_name='node',
            name='military_organization',
        ),
        migrations.AddField(
            model_name='node',
            name='military_organization',
            field=models.ManyToManyField(blank=True, related_name='military_organization', to='configurator.MilitaryOrganization'),
        ),
    ]
