# Generated by Django 3.2.6 on 2022-08-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0013_auto_20220812_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='commander',
            field=models.ManyToManyField(blank=True, null=True, related_name='commander', to='configurator.MilitaryOrganization'),
        ),
        migrations.AlterField(
            model_name='node',
            name='military_organization',
            field=models.ManyToManyField(blank=True, null=True, related_name='military_organization', to='configurator.MilitaryOrganization'),
        ),
        migrations.AlterField(
            model_name='node',
            name='similar',
            field=models.ManyToManyField(blank=True, null=True, related_name='similar', to='configurator.MilitaryOrganization'),
        ),
        migrations.AlterField(
            model_name='node',
            name='subordinate',
            field=models.ManyToManyField(blank=True, null=True, related_name='subordinate', to='configurator.MilitaryOrganization'),
        ),
    ]
