# Generated by Django 3.2.6 on 2022-08-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0014_auto_20220812_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='commander',
        ),
        migrations.RemoveField(
            model_name='node',
            name='similar',
        ),
        migrations.RemoveField(
            model_name='node',
            name='subordinate',
        ),
    ]
