# Generated by Django 3.2.6 on 2022-08-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0015_auto_20220812_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='military_organization',
        ),
        migrations.AddField(
            model_name='node',
            name='military_organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='military_organization', to='configurator.militaryorganization'),
            preserve_default=False,
        ),
    ]
