# Generated by Django 3.2.6 on 2022-08-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0016_auto_20220812_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='commander',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commander', to='configurator.militaryorganization'),
            preserve_default=False,
        ),
    ]
