# Generated by Django 3.2.6 on 2022-08-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0017_node_commander'),
    ]

    operations = [
        migrations.RenameField(
            model_name='militaryorganization',
            old_name='kind',
            new_name='subkind',
        ),
    ]
