# Generated by Django 3.2.6 on 2022-08-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0018_rename_kind_militaryorganization_subkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='position_node',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
