# Generated by Django 3.2.6 on 2022-09-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0019_node_position_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='commander',
        ),
        migrations.AddField(
            model_name='militaryorganization',
            name='commander',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryorganization'),
            preserve_default=False,
        ),
    ]
