# Generated by Django 3.2.6 on 2022-09-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0020_auto_20220909_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryorganization',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryorganization'),
        ),
    ]
