# Generated by Django 3.2.6 on 2022-09-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0021_alter_militaryorganization_commander'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='check_position',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='v_max',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='v_min',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='x_max',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='x_min',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='y_max',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='y_min',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='position_node',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
