# Generated by Django 3.2.6 on 2022-09-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0022_auto_20220910_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='v_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='x_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='x_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='y_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='y_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
