# Generated by Django 3.2.6 on 2022-09-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0023_auto_20220916_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='ip',
            new_name='ip_intf0',
        ),
        migrations.AddField(
            model_name='interface',
            name='ip_intf1',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
