# Generated by Django 3.2.6 on 2022-09-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0024_auto_20220917_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='check_position',
        ),
        migrations.RemoveField(
            model_name='node',
            name='position_node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='v_max',
        ),
        migrations.RemoveField(
            model_name='node',
            name='v_min',
        ),
        migrations.RemoveField(
            model_name='node',
            name='x_max',
        ),
        migrations.RemoveField(
            model_name='node',
            name='x_min',
        ),
        migrations.RemoveField(
            model_name='node',
            name='y_max',
        ),
        migrations.RemoveField(
            model_name='node',
            name='y_min',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='check_position',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='position_node',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='v_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='v_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='x_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='x_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='y_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='y_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='check_position',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='position_node',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='v_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='v_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='x_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='x_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='y_max',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='y_min',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
