# Generated by Django 3.2.6 on 2022-09-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0025_auto_20220922_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='antennaGain',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='radius',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='antennaGain',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='radius',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
