# Generated by Django 3.2.6 on 2022-09-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0026_auto_20220922_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspoint',
            old_name='radius',
            new_name='range',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='radius',
            new_name='range',
        ),
    ]
