# Generated by Django 3.2.6 on 2022-09-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0027_auto_20220922_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspoint',
            old_name='antennaGain',
            new_name='antenna_gain',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='antennaGain',
            new_name='antenna_gain',
        ),
    ]
