# Generated by Django 3.2.6 on 2022-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0028_auto_20220922_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='txpower_intf0',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='interface',
            name='txpower_intf1',
            field=models.IntegerField(default=15),
        ),
    ]
