# Generated by Django 3.2.6 on 2022-11-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0029_auto_20221102_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemeasurement',
            name='random_choice',
            field=models.IntegerField(default=1),
        ),
    ]
