# Generated by Django 3.2.6 on 2022-11-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0030_performancemeasurement_random_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('Military', 'Military'), ('Platform', 'Platform')], max_length=30)),
                ('v_min', models.FloatField(blank=True, max_length=30, null=True)),
                ('v_max', models.FloatField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configurator.resource')),
                ('category', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
            ],
            bases=('configurator.resource',),
        ),
    ]
