# Generated by Django 3.2.6 on 2022-11-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0031_platform_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='resource',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='configurator.resource'),
            preserve_default=False,
        ),
    ]
