# Generated by Django 3.2.6 on 2022-11-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0031_commdevicecarrier_militaryplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='carrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carrier', to='configurator.commdevicecarrier'),
            preserve_default=False,
        ),
    ]
