# Generated by Django 3.2.6 on 2022-11-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0032_node_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='v_max',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='v_min',
        ),
        migrations.RemoveField(
            model_name='station',
            name='v_max',
        ),
        migrations.RemoveField(
            model_name='station',
            name='v_min',
        ),
    ]
