# Generated by Django 3.2.6 on 2022-11-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0033_auto_20221117_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='v_max',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='v_min',
        ),
        migrations.RemoveField(
            model_name='node',
            name='test',
        ),
        migrations.RemoveField(
            model_name='station',
            name='v_max',
        ),
        migrations.RemoveField(
            model_name='station',
            name='v_min',
        ),
    ]
