# Generated by Django 3.2.6 on 2022-11-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0034_auto_20221117_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='test',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
