# Generated by Django 3.2.6 on 2022-11-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0035_node_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='test',
        ),
    ]
