# Generated by Django 3.2.6 on 2023-03-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0036_remove_node_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=30)),
                ('Commdevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='configurator.node')),
                ('MilitaryOrganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryorganization')),
                ('MilitaryPlatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='militaryplatform', to='configurator.militaryplatform')),
            ],
            options={
                'db_table': 'MilitaryPerson',
            },
        ),
    ]
