# Generated by Django 3.2.6 on 2023-03-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0037_militaryperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='militaryperson',
            old_name='Commdevice',
            new_name='CommDevice',
        ),
    ]
