# Generated by Django 3.2.6 on 2023-03-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0038_rename_commdevice_militaryperson_commdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militaryperson',
            name='MilitaryPlatform',
        ),
        migrations.AddField(
            model_name='militaryperson',
            name='CommDeviceCarrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commdevicecarrier', to='configurator.commdevicecarrier'),
            preserve_default=False,
        ),
    ]
