# Generated by Django 3.2.6 on 2023-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0039_auto_20230319_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commdevicecarrier',
            name='type',
            field=models.CharField(choices=[('Military as carrier', 'Military as carrier'), ('Platform', 'Platform')], max_length=30),
        ),
    ]
