# Generated by Django 3.2.6 on 2023-03-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0040_alter_commdevicecarrier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commdevicecarrier',
            name='type',
            field=models.CharField(choices=[('Military As Carrier', 'Military As Carrier'), ('Military Platform', 'Military Platform')], max_length=30),
        ),
    ]
