# Generated by Django 3.2.6 on 2023-03-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0042_auto_20230319_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='commdevicecarrier',
            name='VisibilityRange',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
