# Generated by Django 3.2.6 on 2023-03-20 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0044_remove_militaryperson_commdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='militaryperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryperson'),
            preserve_default=False,
        ),
    ]
