# Generated by Django 3.2.6 on 2023-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0045_node_militaryperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryScenario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'MilitaryScenario',
                'verbose_name_plural': 'MilitaryScenario',
                'db_table': 'MilitaryScenario',
            },
        ),
    ]
