# Generated by Django 3.2.6 on 2023-03-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0046_militaryscenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryorganization',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryscenario'),
        ),
    ]
