# Generated by Django 3.2.6 on 2023-03-28 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0048_militaryperson_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryscenario'),
        ),
    ]
