# Generated by Django 3.2.6 on 2023-03-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0049_testplan_scenario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='militaryperson',
            options={'verbose_name': 'MilitaryPerson', 'verbose_name_plural': 'MilitaryPerson'},
        ),
        migrations.AlterModelTable(
            name='militaryperson',
            table='MilitaryPersonn',
        ),
    ]
