# Generated by Django 3.2.6 on 2023-03-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0050_auto_20230328_0236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='militaryperson',
            table='MilitaryPerson',
        ),
    ]
