# Generated by Django 3.2.6 on 2023-03-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0051_alter_militaryperson_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='node',
            name='military_organization',
        ),
    ]
