# Generated by Django 3.2.6 on 2023-04-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0052_auto_20230328_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MilitaryAsCarrier',
        ),
    ]
