# Generated by Django 3.2.6 on 2023-04-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0055_alter_militaryorganizationpowertype_commander'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryorganization',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryorganizationpowertype'),
        ),
    ]
