# Generated by Django 3.2.6 on 2023-04-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0056_militaryorganization_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militaryorganization',
            name='subkind',
        ),
    ]
