# Generated by Django 3.2.6 on 2023-04-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0057_remove_militaryorganization_subkind'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfacePowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('txpower', models.IntegerField(default=15)),
            ],
            options={
                'db_table': 'InterfacePowerType',
            },
        ),
    ]
