# Generated by Django 3.2.6 on 2023-04-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0059_commdevicecarrier_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryplatform',
            name='MilitaryOrganization',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='configurator.militaryorganization'),
            preserve_default=False,
        ),
    ]
