# Generated by Django 3.2.6 on 2023-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0060_militaryplatform_militaryorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacepowertype',
            name='frequency',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='militaryplatform',
            name='category',
            field=models.CharField(choices=[('armored', 'Armored')], default='armored', max_length=30),
        ),
    ]
