# Generated by Django 3.2.6 on 2023-04-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0002_auto_20230403_2318'),
        ('configurator', '0061_auto_20230403_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='militaryperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.military_person'),
        ),
    ]
