# Generated by Django 3.2.6 on 2023-04-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MilitaryPerson',
            new_name='Military_Person',
        ),
        migrations.RenameModel(
            old_name='MilitaryPlatform',
            new_name='Military_Platform',
        ),
    ]
