# Generated by Django 3.2.6 on 2023-04-04 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0063_auto_20230404_0130'),
        ('militaryScenarioConf', '0002_auto_20230403_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Military_Scenario',
            new_name='MilitaryScenario',
        ),
        migrations.AlterModelOptions(
            name='militaryscenario',
            options={'verbose_name': 'MilitaryScenario', 'verbose_name_plural': 'MilitaryScenario'},
        ),
        migrations.AlterModelTable(
            name='militaryscenario',
            table='MilitaryScenario',
        ),
    ]
