# Generated by Django 3.2.6 on 2023-04-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0003_auto_20230404_0135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Military_OrganizationPowerType',
            new_name='MilitaryOrganizationPowerType',
        ),
        migrations.AlterModelOptions(
            name='militaryorganizationpowertype',
            options={'verbose_name': 'MilitaryOrganizationPowerType', 'verbose_name_plural': 'MilitaryOrganizationPowerTypes'},
        ),
        migrations.AlterModelTable(
            name='militaryorganizationpowertype',
            table='MilitaryOrganizationPowerType',
        ),
    ]
