# Generated by Django 3.2.6 on 2023-04-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0063_auto_20230404_0130'),
        ('militaryScenarioConf', '0004_auto_20230404_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Military_Person',
            new_name='MilitaryPerson',
        ),
        migrations.AlterModelOptions(
            name='militaryperson',
            options={'verbose_name': 'MilitaryPerson', 'verbose_name_plural': 'MilitaryPerson'},
        ),
        migrations.AlterModelTable(
            name='militaryperson',
            table='MilitaryPerson',
        ),
    ]
