# Generated by Django 3.2.6 on 2023-04-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0005_auto_20230404_0147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Military_Organization',
            new_name='MilitaryOrganization',
        ),
        migrations.AlterModelOptions(
            name='militaryorganization',
            options={'verbose_name': 'MilitaryOrganization', 'verbose_name_plural': 'MilitaryOrganization'},
        ),
        migrations.AlterModelTable(
            name='militaryorganization',
            table='MilitaryOrganization',
        ),
    ]
