# Generated by Django 3.2.6 on 2023-04-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0006_auto_20230404_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryscenario',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
