# Generated by Django 3.2.6 on 2023-04-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0007_militaryscenario_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='military_platform',
            table=None,
        ),
    ]
