# Generated by Django 3.2.6 on 2023-04-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0008_alter_military_platform_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryperson',
            name='CommDevice_Carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commdevicecarrier', to='militaryScenarioConf.commdevice_carrier'),
        ),
    ]
