# Generated by Django 3.2.6 on 2023-04-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0009_alter_militaryperson_commdevice_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militaryperson',
            name='CommDevice_Carrier',
        ),
    ]
