# Generated by Django 3.2.6 on 2023-04-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0010_remove_militaryperson_commdevice_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('VisibilityRange', models.FloatField(blank=True, max_length=30, null=True)),
                ('v_min', models.FloatField(blank=True, max_length=30, null=True)),
                ('v_max', models.FloatField(blank=True, max_length=30, null=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryscenario')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('carrier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='militaryScenarioConf.carrier')),
                ('category', models.CharField(choices=[('armored', 'Armored')], default='armored', max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('Military_Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militaryScenarioConf.militaryorganization')),
            ],
            bases=('militaryScenarioConf.carrier',),
        ),
    ]
