# Generated by Django 3.2.6 on 2023-04-06 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0011_carrier_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryperson',
            name='CommDevice_Carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commdevicecarrier', to='militaryScenarioConf.commdevice_carrier'),
        ),
    ]
