# Generated by Django 3.2.6 on 2023-04-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0012_militaryperson_commdevice_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarani',
            fields=[
                ('platform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='militaryScenarioConf.platform')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('militaryScenarioConf.platform',),
        ),
        migrations.RemoveField(
            model_name='platform',
            name='kind',
        ),
    ]
