# Generated by Django 3.2.6 on 2023-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militaryScenarioConf', '0014_alter_militaryperson_commdevice_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryscenario',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
